version: "3.8"

services:

  web:
    build: .
    container_name: web_techuniverse
    ports:
      - "8080:80" # Puerto público para tu API
    depends_on:
      - db
    volumes:
      - ./techuniverse:/var/www/html
    networks:
      - backend-net
    restart: always

  db:
    image: mysql:5.7
    container_name: db_techuniverse
    environment:
      MYSQL_ROOT_PASSWORD: usuario1
      MYSQL_DATABASE: techstore
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
    volumes:
      - db_data:/var/lib/mysql
      - ./techuniverse/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-net
    restart: always

  phpmyadmin:
    image: phpmyadmin:5
    container_name: pma_techuniverse
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - "8081:80" # Solo usar mediante túnel SSH
    networks:
      - backend-net
    restart: always

volumes:
  db_data:


networks:
  backend-net:
    driver: bridge
